# 1. Import Pandas and Numpy

In [1]:
import pandas as pd
import numpy as np

# 2. Load the CSV Dataset

In [2]:
df = pd.read_csv("Student_Dataset.csv")
df

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

# 3. Display the First & Last Few Rows

In [3]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [4]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

# 5. Display Random Samples

In [5]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar

In [6]:
df.sample(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad

# 6. Check the Shape of the Dataset

In [7]:
df.shape

(25, 7)

# 7. Display Column Names

In [8]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

# 8. Display the Dataset Index

In [9]:
df.index

RangeIndex(start=0, stop=25, step=1)

# 9. Check Data Types

In [10]:
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

# 10. Get Complete Dataset Information

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

# 11. Generate Descriptive Statistics

In [12]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

# 12. Generate Statistics for All Columns

In [13]:
df.describe(include="all")

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
count,25.000000,25,25.000000,25,24.000000,24.000000,24
unique,NaN,25,NaN,3,NaN,NaN,13
top,NaN,Aarav Sharma,NaN,Data Science,NaN,NaN,Srinagar
freq,NaN,1,NaN,9,NaN,NaN,6
mean,1013.000000,NaN,20.000000,NaN,82.250000,87.083333,NaN
std,7.359801,NaN,1.414214,NaN,8.689074,7.252686,NaN
min,1001.000000,NaN,18.000000,NaN,68.000000,72.000000,NaN
25%,1007.000000,NaN,19.000000,NaN,75.500000,82.750000,NaN
50%,1013.000000,NaN,20.000000,NaN,82.500000,88.000000,NaN
75%,1019.000000,NaN,21.000000,NaN,89.250000,92.250000,NaN
max,1025.000000,NaN,23.000000,NaN,96.000000,98.000000,NaN

# 13. Check Missing Values

In [14]:
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

# 14. Check Whether Missing Values Exist

In [15]:
if df.isnull().values.any():
    print("Missing values are present in the dataset.")
else:
    print("No missing values are present in the dataset.")

Missing values are present in the dataset.

# 15. Calculate Missing Value Percentage

In [16]:
# Calculate percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100
print("Missing Value Percentage:")
print(missing_percentage)

Missing Value Percentage:
Student_ID               0.0
Name                     0.0
Age                      0.0
Course                   0.0
Marks                    4.0
Attendance_Percentage    4.0
City                     4.0
dtype: float64

# 16. Check Duplicate Rows

In [17]:
df.duplicated().sum()

np.int64(0)

# 17. Check Unique Values

In [18]:
df.nunique()

Student_ID               25
Name                     25
Age                       6
Course                    3
Marks                    24
Attendance_Percentage    22
City                     13
dtype: int64

# 18. Display Column-Wise Information

In [19]:
summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
summary

                  Column Data Type  Missing Values  Unique Values
0             Student_ID     int64               0             25
1                   Name    object               0             25
2                    Age     int64               0              6
3                 Course    object               0              3
4                  Marks   float64               1             24
5  Attendance_Percentage   float64               1             22
6                   City    object               1             13